name = "playground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Playground"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0"

[[lean_lib]]
name = "Playground"
